# Arc balanced-rest pseudobulk audit

This notebook recreates the KaroSpace balanced-rest calculation for `Arc` in the requested annotation categories. KaroSpace fits one shared `~ replicate + annotation` DESeq2 model, then tests each category against the equally weighted mean of every other retained annotation category. This is not a pooled all-other-cells rest comparison.

In [ ]:
# Parameters: edit these for your dataset
H5AD_PATH = "/Users/bastien.herve/Downloads/hipp_celltyped_v3_noLowQ.h5ad"

# GROUPBY is the annotation/color column used for DE Genes, e.g. cell type annotation.
GROUPBY = "major_celltype"

# REPLICATE must match the KaroSpace export groupby/section column, often sample_id.
REPLICATE = "mouse_id"

GENE = "Sox10"
SOURCE_LABELS = ["COP", "Oligodendrocytes"]

# Same defaults as KaroSpace export unless you changed them.
COUNTS_LAYER = "counts"  # set to None to force adata.X
MIN_CELLS = 20
MIN_REPLICATES = 2
MIN_PCT_EXPRESSED = 0.2
P_ADJUST_METHOD = "fdr_bh"
PADJ_CUTOFF = 0.05
LOG2FC_CUTOFF = 0.5
FIT_TYPE = "mean"
DIAGNOSTICS = "pairwise"  # "none" or "pairwise"

In [18]:
from pathlib import Path
import difflib

import anndata as ad
import numpy as np
import pandas as pd
import scipy.sparse as sp

from karospace.pseudobulk import (
    _as_count_matrix,
    _to_dense_counts,
    compute_pseudobulk_group_de,
)

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 200)


def tiny_pseudocount():
    return float(np.nextafter(0.0, 1.0))


def log2_with_tiny_pseudocount(numerator, denominator):
    tiny = tiny_pseudocount()
    a = max(0.0, float(numerator) if np.isfinite(numerator) else 0.0) + tiny
    b = max(0.0, float(denominator) if np.isfinite(denominator) else 0.0) + tiny
    return float(np.log2(a) - np.log2(b))


def find_category(categories, wanted):
    """Resolve labels robustly while still making mismatches explicit."""
    wanted = str(wanted)
    categories = [str(c) for c in categories]
    if wanted in categories:
        return wanted
    lower = {c.lower(): c for c in categories}
    if wanted.lower() in lower:
        return lower[wanted.lower()]
    contains = [c for c in categories if wanted.lower() in c.lower() or c.lower() in wanted.lower()]
    if len(contains) == 1:
        return contains[0]
    close = difflib.get_close_matches(wanted, categories, n=8, cutoff=0.35)
    raise KeyError(
        f"Could not resolve category {wanted!r}. Close matches: {close}. "
        "Set SOURCE_LABELS to the exact category names from adata.obs[GROUPBY].cat.categories."
    )


def find_gene(var_names, wanted):
    genes = [str(g) for g in var_names]
    if wanted in genes:
        return wanted
    lower = {g.lower(): g for g in genes}
    if wanted.lower() in lower:
        return lower[wanted.lower()]
    close = difflib.get_close_matches(wanted, genes, n=8, cutoff=0.5)
    raise KeyError(f"Gene {wanted!r} not found. Close matches: {close}")


def one_gene_result(result, gene):
    if not result:
        return {"available": False, "reason": "missing_result"}
    if result.get("available") is False:
        return {
            "available": False,
            "reason": result.get("reason"),
            "details": result.get("details"),
            "n_source": result.get("n_source"),
            "n_reference": result.get("n_reference"),
            "min_cells_required": result.get("min_cells_required"),
            "min_replicates_required": result.get("min_replicates_required"),
        }
    genes = [str(g) for g in result.get("genes", [])]
    if gene not in genes:
        return {
            "available": True,
            "gene_present": False,
            "n_result_genes": len(genes),
            "method": result.get("method"),
            "min_pct_expressed": result.get("min_pct_expressed"),
        }
    i = genes.index(gene)
    log2fc = result.get("log2foldchanges", result.get("logfoldchanges", []))[i]
    padj = result.get("pvals_adj", [None] * len(genes))[i]
    return {
        "available": True,
        "gene_present": True,
        "method": result.get("method"),
        "counts_layer": result.get("counts_layer"),
        "n_source": result.get("n_source"),
        "n_reference": result.get("n_reference"),
        "n_replicates": result.get("n_replicates"),
        "base_mean": result.get("base_mean", [None] * len(genes))[i],
        "log2FC": log2fc,
        "stat": result.get("scores", [None] * len(genes))[i],
        "pvalue": result.get("pvals", [None] * len(genes))[i],
        "padj": padj,
        "pct_source": result.get("pct_source", [None] * len(genes))[i],
        "pct_rest": result.get("pct_reference", [None] * len(genes))[i],
        "padj_cutoff": result.get("padj_cutoff"),
        "log2fc_cutoff": result.get("log2fc_cutoff"),
        "passes_DE_star": (padj is not None and log2fc is not None and padj <= result.get("padj_cutoff", 0.05) and log2fc >= result.get("log2fc_cutoff", 0.5)),
    }

In [19]:
adata = ad.read_h5ad(H5AD_PATH)
print(adata)

missing_obs = [c for c in [GROUPBY, REPLICATE] if c not in adata.obs.columns]
if missing_obs:
    raise KeyError(f"Missing obs columns: {missing_obs}")

group_col = adata.obs[GROUPBY]
if not isinstance(group_col.dtype, pd.CategoricalDtype):
    group_col = group_col.astype("category")
categories = [str(c) for c in group_col.cat.categories]
gene = find_gene(adata.var_names, GENE)
source_labels = [find_category(categories, label) for label in SOURCE_LABELS]

print(f"Gene: {gene}")
print(f"GROUPBY={GROUPBY!r}: {len(categories)} categories")
print(source_labels)
pd.Series(categories, name="categories").to_frame().head(50)

AnnData object with n_obs × n_vars = 1713896 × 347
    obs: 'cell_id_old', 'x_centroid', 'y_centroid', 'Xenium_run', 'cell_id_new', 'inside_polygon', 'strain', 'mouse_id', 'region', 'class_label', 'class_name', 'class_bootstrapping_probability', 'subclass_label', 'subclass_name', 'subclass_bootstrapping_probability', 'supertype_label', 'supertype_name', 'supertype_bootstrapping_probability', 'cluster_label', 'cluster_name', 'cluster_alias', 'cluster_bootstrapping_probability', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_10_genes', 'pct_counts_in_top_20_genes', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_150_genes', 'n_counts', 'n_genes', 'doublet_score', 'predicted_doublet', 'is_it_doublet', 'Batch', 'Slide', 'class_name_high_prob', 'subclass_name_high_prob', 'leiden_1', 'major_celltype', 'final_celltype_annotation', 'final_celltype_annotation_v2', 'is_low_quality', 'final_celltype_annotation_v3'
    var: 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts'
    uns: 'final_celltype_annotation_colors', 'leiden_1', 'log1p', 'major_celltype_colors', 'neighbors', 'pca', 'scrublet', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'
Gene: Sox10
GROUPBY='major_celltype': 12 categories
['COP', 'Oligodendrocytes']

                              categories
0                             Astrocytes
1                                    COP
2                         Choroid plexus
3                      Endothelial cells
4                        Ependymal cells
5                     Excitatory neurons
6                     Inhibitory neurons
7   Microglia / perivascular macrophages
8                                    OPC
9                       Oligodendrocytes
10       Pericytes / smooth muscle cells
11                                  VLMC

In [20]:
# Run the same KaroSpace shared-fit balanced-rest pseudobulk DE function used by export_to_html.
de = compute_pseudobulk_group_de(
    adata,
    GROUPBY,
    replicate=REPLICATE,
    counts_layer=COUNTS_LAYER,
    min_cells=MIN_CELLS,
    min_replicates=MIN_REPLICATES,
    min_pct_expressed=MIN_PCT_EXPRESSED,
    p_adjust_method=P_ADJUST_METHOD,
    padj_cutoff=PADJ_CUTOFF,
    log2fc_cutoff=LOG2FC_CUTOFF,
    fit_type=FIT_TYPE,
    diagnostics=DIAGNOSTICS,
)

rows = []
for source in source_labels:
    result = ((de or {}).get(source) or {}).get("__rest__")
    rows.append({"source": source, "reference": "balanced rest", **one_gene_result(result, gene)})
summary = pd.DataFrame(rows)
summary

    - 12 categories -> 132 directed comparisons plus 12 category-vs-rest contrasts (66 pairwise DESeq2 fits)
      - Astrocytes vs COP: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Astrocytes vs Choroid plexus: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Astrocytes vs Endothelial cells: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Astrocytes vs Ependymal cells: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Astrocytes vs Excitatory neurons: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Astrocytes vs Inhibitory neurons: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Astrocytes vs Microglia / perivascular macrophages: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Astrocytes vs OPC: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Astrocytes vs Oligodendrocytes: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Astrocytes vs Pericytes / smooth muscle cells: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Astrocytes vs VLMC: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Astrocytes vs rest: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - COP vs Astrocytes: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - COP vs Choroid plexus: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - COP vs Endothelial cells: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - COP vs Ependymal cells: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - COP vs Excitatory neurons: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - COP vs Inhibitory neurons: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - COP vs Microglia / perivascular macrophages: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - COP vs OPC: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - COP vs Oligodendrocytes: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - COP vs Pericytes / smooth muscle cells: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - COP vs VLMC: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - COP vs rest: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Choroid plexus vs Astrocytes: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Choroid plexus vs COP: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Choroid plexus vs Endothelial cells: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Choroid plexus vs Ependymal cells: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Choroid plexus vs Excitatory neurons: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Choroid plexus vs Inhibitory neurons: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Choroid plexus vs Microglia / perivascular macrophages: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Choroid plexus vs OPC: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Choroid plexus vs Oligodendrocytes: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Choroid plexus vs Pericytes / smooth muscle cells: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Choroid plexus vs VLMC: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Choroid plexus vs rest: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Endothelial cells vs Astrocytes: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Endothelial cells vs COP: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Endothelial cells vs Choroid plexus: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Endothelial cells vs Ependymal cells: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Endothelial cells vs Excitatory neurons: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Endothelial cells vs Inhibitory neurons: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Endothelial cells vs Microglia / perivascular macrophages: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Endothelial cells vs OPC: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Endothelial cells vs Oligodendrocytes: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Endothelial cells vs Pericytes / smooth muscle cells: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Endothelial cells vs VLMC: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Endothelial cells vs rest: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Ependymal cells vs Astrocytes: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Ependymal cells vs COP: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Ependymal cells vs Choroid plexus: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Ependymal cells vs Endothelial cells: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Ependymal cells vs Excitatory neurons: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Ependymal cells vs Inhibitory neurons: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Ependymal cells vs Microglia / perivascular macrophages: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Ependymal cells vs OPC: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Ependymal cells vs Oligodendrocytes: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Ependymal cells vs Pericytes / smooth muscle cells: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Ependymal cells vs VLMC: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Ependymal cells vs rest: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Excitatory neurons vs Astrocytes: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Excitatory neurons vs COP: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Excitatory neurons vs Choroid plexus: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Excitatory neurons vs Endothelial cells: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Excitatory neurons vs Ependymal cells: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Excitatory neurons vs Inhibitory neurons: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Excitatory neurons vs Microglia / perivascular macrophages: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Excitatory neurons vs OPC: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Excitatory neurons vs Oligodendrocytes: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Excitatory neurons vs Pericytes / smooth muscle cells: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Excitatory neurons vs VLMC: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Excitatory neurons vs rest: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Inhibitory neurons vs Astrocytes: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Inhibitory neurons vs COP: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Inhibitory neurons vs Choroid plexus: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Inhibitory neurons vs Endothelial cells: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Inhibitory neurons vs Ependymal cells: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Inhibitory neurons vs Excitatory neurons: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Inhibitory neurons vs Microglia / perivascular macrophages: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Inhibitory neurons vs OPC: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Inhibitory neurons vs Oligodendrocytes: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Inhibitory neurons vs Pericytes / smooth muscle cells: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Inhibitory neurons vs VLMC: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Inhibitory neurons vs rest: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Microglia / perivascular macrophages vs Astrocytes: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Microglia / perivascular macrophages vs COP: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Microglia / perivascular macrophages vs Choroid plexus: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Microglia / perivascular macrophages vs Endothelial cells: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Microglia / perivascular macrophages vs Ependymal cells: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Microglia / perivascular macrophages vs Excitatory neurons: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Microglia / perivascular macrophages vs Inhibitory neurons: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Microglia / perivascular macrophages vs OPC: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Microglia / perivascular macrophages vs Oligodendrocytes: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Microglia / perivascular macrophages vs Pericytes / smooth muscle cells: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Microglia / perivascular macrophages vs VLMC: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Microglia / perivascular macrophages vs rest: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - OPC vs Astrocytes: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - OPC vs COP: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - OPC vs Choroid plexus: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - OPC vs Endothelial cells: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - OPC vs Ependymal cells: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - OPC vs Excitatory neurons: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - OPC vs Inhibitory neurons: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - OPC vs Microglia / perivascular macrophages: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - OPC vs Oligodendrocytes: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - OPC vs Pericytes / smooth muscle cells: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - OPC vs VLMC: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - OPC vs rest: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Oligodendrocytes vs Astrocytes: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Oligodendrocytes vs COP: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Oligodendrocytes vs Choroid plexus: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Oligodendrocytes vs Endothelial cells: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Oligodendrocytes vs Ependymal cells: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Oligodendrocytes vs Excitatory neurons: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Oligodendrocytes vs Inhibitory neurons: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Oligodendrocytes vs Microglia / perivascular macrophages: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Oligodendrocytes vs OPC: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Oligodendrocytes vs Pericytes / smooth muscle cells: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Oligodendrocytes vs VLMC: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Oligodendrocytes vs rest: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Pericytes / smooth muscle cells vs Astrocytes: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Pericytes / smooth muscle cells vs COP: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Pericytes / smooth muscle cells vs Choroid plexus: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Pericytes / smooth muscle cells vs Endothelial cells: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Pericytes / smooth muscle cells vs Ependymal cells: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Pericytes / smooth muscle cells vs Excitatory neurons: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Pericytes / smooth muscle cells vs Inhibitory neurons: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Pericytes / smooth muscle cells vs Microglia / perivascular macrophages: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Pericytes / smooth muscle cells vs OPC: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Pericytes / smooth muscle cells vs Oligodendrocytes: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Pericytes / smooth muscle cells vs VLMC: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - Pericytes / smooth muscle cells vs rest: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - VLMC vs Astrocytes: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - VLMC vs COP: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - VLMC vs Choroid plexus: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - VLMC vs Endothelial cells: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - VLMC vs Ependymal cells: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - VLMC vs Excitatory neurons: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - VLMC vs Inhibitory neurons: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - VLMC vs Microglia / perivascular macrophages: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - VLMC vs OPC: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - VLMC vs Oligodendrocytes: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - VLMC vs Pericytes / smooth muscle cells: using cached reverse fit (28 paired replicates, 56 pseudobulk samples, 347 genes)
      - VLMC vs rest: fitting DESeq2 (28 paired replicates, 56 pseudobulk samples, 347 genes)

,source,reference,available,gene_present,method,counts_layer,n_source,n_reference,n_replicates,base_mean,log2FC,stat,pvalue,padj,pct_source,pct_rest,padj_cutoff,log2fc_cutoff,passes_DE_star
0,COP,__rest__,True,True,pseudobulk-deseq2,counts,8190,1705706,28,9054.055210,2.598985,93.241430,0.0,4.940656e-324,0.771551,0.163532,0.05,0.5,True
1,Oligodendrocytes,__rest__,True,True,pseudobulk-deseq2,counts,283292,1430604,28,54709.789108,5.094992,168.064905,0.0,4.940656e-324,0.807764,0.039441,0.05,0.5,True

## Pairwise diagnostics for Arc

With `DIAGNOSTICS = "pairwise"`, KaroSpace stores one PCA/distance payload for each unordered selected pair. It contains only the two annotations and is reused for either contrast direction. `"none"` omits these diagnostics from the exported HTML. Pairwise diagnostics apply only to category-versus-category contrasts; balanced-rest contrasts deliberately omit them because their reference comprises multiple annotations.

In [13]:
expression_matrix, counts_layer_used, warning = _as_count_matrix(adata, COUNTS_LAYER)
if warning:
    print("Warning:", warning)

group_values = group_col.astype(str)
rep_values = adata.obs[REPLICATE].astype(str)
valid = rep_values.notna().to_numpy() & group_values.notna().to_numpy()
valid &= np.asarray(group_col.cat.codes.to_numpy() >= 0, dtype=bool)
valid_indices = np.flatnonzero(valid)

rep_valid = rep_values.iloc[valid_indices].astype(str).to_numpy()
group_valid = group_values.iloc[valid_indices].astype(str).to_numpy()

sample_keys = []
sample_index = {}
rows = np.empty(valid_indices.size, dtype=np.int64)
for i, (rep, grp) in enumerate(zip(rep_valid, group_valid)):
    key = (str(rep), str(grp))
    idx = sample_index.get(key)
    if idx is None:
        idx = len(sample_keys)
        sample_index[key] = idx
        sample_keys.append(key)
    rows[i] = idx

incidence = sp.csr_matrix(
    (np.ones(valid_indices.size, dtype=np.float64), (rows, valid_indices)),
    shape=(len(sample_keys), adata.n_obs),
)
aggregate = _to_dense_counts(incidence @ expression_matrix)
cell_counts = np.bincount(rows, minlength=len(sample_keys)).astype(int)
pb_meta = pd.DataFrame(
    {
        "replicate": [k[0] for k in sample_keys],
        "category": [k[1] for k in sample_keys],
        "n_cells": cell_counts,
    },
    index=[f"pb_{i}" for i in range(len(sample_keys))],
)

gene_idx = [str(g) for g in adata.var_names].index(gene)
pb_meta["gene_counts"] = aggregate[:, gene_idx]
pb_meta["gene_mean_per_cell"] = pb_meta["gene_counts"] / pb_meta["n_cells"].replace(0, np.nan)

audit_rows = []
for source in source_labels:
    source_pb = pb_meta[(pb_meta["category"] == source) & (pb_meta["n_cells"] >= MIN_CELLS)]
    for rep in sorted(source_pb["replicate"].astype(str).unique()):
        src = pb_meta[(pb_meta["replicate"].astype(str) == rep) & (pb_meta["category"] == source) & (pb_meta["n_cells"] >= MIN_CELLS)]
        rest = pb_meta[(pb_meta["replicate"].astype(str) == rep) & (pb_meta["category"] != source)]
        rest_cells = int(rest["n_cells"].sum())
        if src.empty or rest.empty or rest_cells < MIN_CELLS:
            continue
        audit_rows.append(
            {
                "source": source,
                "replicate": rep,
                "source_cells": int(src["n_cells"].iloc[0]),
                "source_arc_counts": int(src["gene_counts"].iloc[0]),
                "source_arc_mean": float(src["gene_mean_per_cell"].iloc[0]),
                "rest_cells": rest_cells,
                "rest_arc_counts": int(rest["gene_counts"].sum()),
                "rest_arc_mean": float(rest["gene_counts"].sum() / rest_cells),
                "rough_log2fc_tiny_pseudocount": log2_with_tiny_pseudocount(src["gene_counts"].iloc[0] / src["n_cells"].iloc[0], rest["gene_counts"].sum() / rest_cells),
            }
        )

replicate_audit = pd.DataFrame(audit_rows)
replicate_audit

,source,replicate,source_cells,source_arc_counts,source_arc_mean,rest_cells,rest_arc_counts,rest_arc_mean,rough_log2fc_tiny_pseudocount
0,COP,261982,273,701,2.567766,57008,25054,0.439482,2.546637
1,COP,264010,257,525,2.042802,58554,20164,0.344366,2.568535
2,COP,264011,266,655,2.462406,61428,20688,0.336785,2.870171
3,COP,311430,244,720,2.950820,58839,24308,0.413127,2.836457
4,COP,350670,244,761,3.118852,62515,27675,0.442694,2.816634
5,COP,437942,293,630,2.150171,61443,25268,0.411243,2.386388
6,COP,437943,282,753,2.670213,60251,23475,0.389620,2.776815
7,COP,437944,346,772,2.231214,67048,26154,0.390079,2.515991
8,COP,437968,225,540,2.400000,59742,21373,0.357755,2.745991
9,COP,439247,341,843,2.472141,74288,34103,0.459065,2.428991
10,COP,455228,345,791,2.292754,62231,22645,0.363886,2.655522
11,COP,489830,290,690,2.379310,50926,17649,0.346562,2.779359
12,COP,508467,343,838,2.443149,65255,29759,0.456042,2.421504
13,COP,600598,343,855,2.492711,75984,27755,0.365274,2.770664
14,COP,600599,388,1150,2.963918,72769,28636,0.393519,2.912999
15,COP,600600,312,721,2.310897,62909,23689,0.376560,2.617502
16,COP,602886,232,578,2.491379,49072,23525,0.479398,2.377650
17,COP,602887,246,644,2.617886,59886,23738,0.396386,2.723423
18,COP,631316,334,958,2.868263,65014,30702,0.472237,2.602595
19,COP,631317,309,874,2.828479,65375,30119,0.460711,2.618092
20,COP,632977,347,732,2.109510,60082,24337,0.405063,2.380689
21,COP,664976,295,627,2.125424,59407,24736,0.416382,2.351771
22,COP,671899,254,467,1.838583,55157,24924,0.451874,2.024602
23,COP,671902,271,674,2.487085,57706,22497,0.389855,2.673444
24,COP,710673,350,779,2.225714,59824,20505,0.342755,2.699017
25,COP,730346,231,584,2.528139,50732,21893,0.431542,2.550502
26,COP,730349,294,776,2.639456,52628,24264,0.461047,2.517254
27,COP,755476,235,514,2.187234,59633,23098,0.387336,2.497451
28,Oligodendrocytes,261982,9121,22642,2.482403,48160,3113,0.064639,5.263195
29,Oligodendrocytes,264010,9122,18065,1.980377,49689,2624,0.052808,5.228862
30,Oligodendrocytes,264011,9268,18474,1.993310,52426,2869,0.054725,5.186829
31,Oligodendrocytes,311430,10002,21584,2.157968,49081,3444,0.070170,4.942681
32,Oligodendrocytes,350670,9846,24733,2.511985,52913,3703,0.069983,5.165683
33,Oligodendrocytes,437942,10518,22600,2.148697,51218,3298,0.064391,5.060450
34,Oligodendrocytes,437943,9400,21096,2.244255,51133,3132,0.061252,5.195335
35,Oligodendrocytes,437944,12438,23634,1.900145,54956,3292,0.059902,4.987350
36,Oligodendrocytes,437968,8989,19130,2.128157,50978,2783,0.054592,5.284766
37,Oligodendrocytes,439247,12774,30235,2.366917,61855,4711,0.076162,4.957794
38,Oligodendrocytes,455228,10955,20156,1.839890,51621,3280,0.063540,4.855810
39,Oligodendrocytes,489830,8527,15899,1.864548,42689,2440,0.057158,5.027737
40,Oligodendrocytes,508467,10930,26715,2.444190,54668,3882,0.071010,5.105181
41,Oligodendrocytes,600598,11967,24326,2.032757,64360,4284,0.066563,4.932572
42,Oligodendrocytes,600599,11802,25849,2.190222,61355,3937,0.064168,5.093089
43,Oligodendrocytes,600600,9899,21366,2.158400,53322,3044,0.057087,5.240653
44,Oligodendrocytes,602886,8774,21457,2.445521,40530,2646,0.065285,5.227247
45,Oligodendrocytes,602887,9445,21029,2.226469,50687,3353,0.066151,5.072849
46,Oligodendrocytes,631316,11072,27560,2.489162,54276,4100,0.075540,5.042279
47,Oligodendrocytes,631317,12233,26932,2.201586,53451,4061,0.075976,4.856853
48,Oligodendrocytes,632977,9178,21590,2.352364,51251,3479,0.067882,5.114947
49,Oligodendrocytes,664976,10165,22261,2.189966,49537,3102,0.062620,5.128144
50,Oligodendrocytes,671899,10914,22691,2.079073,44497,2700,0.060678,5.098617
51,Oligodendrocytes,671902,9839,20007,2.033438,48138,3164,0.065728,4.951276
52,Oligodendrocytes,710673,8532,18274,2.141819,51642,3010,0.058286,5.199546
53,Oligodendrocytes,730346,8689,19948,2.295776,42274,2529,0.059824,5.262114
54,Oligodendrocytes,730349,9356,22088,2.360838,43566,2952,0.067759,5.122737
55,Oligodendrocytes,755476,9537,20772,2.178043,50331,2840,0.056426,5.270517

## Balanced-rest calculation

For each source category, this notebook shows cell-level descriptive values and the KaroSpace result from the shared model. The rough pooled rest mean is only descriptive: it is not the DESeq2 balanced-rest reference.

In [14]:
from IPython.display import display

def gene_values_from_matrix(matrix, mask, gene_idx):
    if sp.issparse(matrix):
        return np.asarray(matrix[mask, gene_idx].toarray()).ravel()
    return np.asarray(matrix[mask, gene_idx]).ravel()

def breakdown_balanced_rest(source):
    source = str(source)
    result = ((de or {}).get(source) or {}).get("__rest__")
    source_mask = (group_values.to_numpy() == source) & valid
    other_mask = (group_values.to_numpy() != source) & valid
    source_values = gene_values_from_matrix(expression_matrix, source_mask, gene_idx)
    other_values = gene_values_from_matrix(expression_matrix, other_mask, gene_idx)

    descriptive = pd.DataFrame([{
        "source": source,
        "source_cells": int(source_mask.sum()),
        "all_other_cells": int(other_mask.sum()),
        "source_mean_per_cell": float(source_values.mean()) if source_values.size else np.nan,
        "pooled_other_mean_per_cell": float(other_values.mean()) if other_values.size else np.nan,
        "note": "The pooled-other mean is descriptive only; DESeq2 uses an equal-category-weight balanced-rest contrast.",
    }])
    display(descriptive)

    arc_result = one_gene_result(result, gene)
    display(pd.DataFrame([{"source": source, "reference": "balanced rest", **arc_result}]))

    diagnostics = None  # Balanced-rest contrasts deliberately have no pairwise PCA/distance payload.
    if diagnostics:
        display(pd.DataFrame({
            "label": diagnostics.get("labels", []),
            "replicate": diagnostics.get("replicates", []),
            "group": diagnostics.get("groups", []),
            "n_cells": diagnostics.get("n_cells", []),
            "library_size": diagnostics.get("library_size", []),
        }))
    return {
        "source": source,
        "source_mean": descriptive.loc[0, "source_mean_per_cell"],
        "rest_mean": descriptive.loc[0, "pooled_other_mean_per_cell"],
        "included_replicates": sorted(set((diagnostics or {}).get("replicates", []))),
        "de_result": arc_result,
    }

In [15]:
breakdowns = {source: breakdown_balanced_rest(source) for source in source_labels}

comparison_rows = []
for source, payload in breakdowns.items():
    de_result = payload["de_result"]
    comparison_rows.append({
        "source": source,
        "descriptive_source_mean": payload["source_mean"],
        "descriptive_pooled_other_mean": payload["rest_mean"],
        "DESeq2_balanced_rest_log2FC": de_result.get("log2FC"),
        "DESeq2_padj": de_result.get("padj"),
        "pct_source": de_result.get("pct_source"),
        "pct_reference": de_result.get("pct_rest"),
        "passes_DE_star": de_result.get("passes_DE_star"),
        "fit_replicates": ", ".join(payload["included_replicates"]),
    })
pd.DataFrame(comparison_rows)

==========================================================================================
Sox10: COP vs rest
==========================================================================================

,step,category,cells,Arc_positive_cells,pct_Arc_positive,Arc_counts_sum,Arc_mean_per_cell
0,1. source cells,COP,8190,6319,0.771551,20152.0,2.460562
1,1. rest cells,all non-source categories,1705706,278938,0.163532,692733.0,0.406127

,step,source_mean,rest_mean,log2(source_mean / rest_mean),log2_with_tiny_pseudocount,note
0,2. pooled rough log2FC,2.460562,0.406127,2.598985,2.598985,This is not DESeq2; it is a rough pooled check.

Step 3. Pooled category components that make up source and rest

,is_source,category,cells,Arc_counts,Arc_mean_per_cell
11,True,COP,8190,20152,2.460562
8,False,Oligodendrocytes,283292,621113,2.192483
7,False,OPC,61452,46037,0.749154
6,False,Microglia / perivascular macrophages,70664,3589,0.050790
3,False,Ependymal cells,29216,895,0.030634
9,False,Pericytes / smooth muscle cells,52581,1479,0.028128
0,False,Astrocytes,244494,6274,0.025661
2,False,Endothelial cells,170126,3728,0.021913
5,False,Inhibitory neurons,198530,2925,0.014733
4,False,Excitatory neurons,531760,6248,0.011750
10,False,VLMC,46200,395,0.008550
1,False,Choroid plexus,17391,50,0.002875

Step 4. Paired replicates used by DESeq2: 28 / required 2

,step,replicate,_pb_group,included,cells,Arc_counts,Arc_mean_per_cell
0,4. DESeq2 paired input,261982,COP,True,273,701,2.567766
1,4. DESeq2 paired input,261982,__rest__,True,57008,25054,0.439482
2,4. DESeq2 paired input,264010,COP,True,257,525,2.042802
3,4. DESeq2 paired input,264010,__rest__,True,58554,20164,0.344366
4,4. DESeq2 paired input,264011,COP,True,266,655,2.462406
5,4. DESeq2 paired input,264011,__rest__,True,61428,20688,0.336785
6,4. DESeq2 paired input,311430,COP,True,244,720,2.950820
7,4. DESeq2 paired input,311430,__rest__,True,58839,24308,0.413127
8,4. DESeq2 paired input,350670,COP,True,244,761,3.118852
9,4. DESeq2 paired input,350670,__rest__,True,62515,27675,0.442694
10,4. DESeq2 paired input,437942,COP,True,293,630,2.150171
11,4. DESeq2 paired input,437942,__rest__,True,61443,25268,0.411243
12,4. DESeq2 paired input,437943,COP,True,282,753,2.670213
13,4. DESeq2 paired input,437943,__rest__,True,60251,23475,0.389620
14,4. DESeq2 paired input,437944,COP,True,346,772,2.231214
15,4. DESeq2 paired input,437944,__rest__,True,67048,26154,0.390079
16,4. DESeq2 paired input,437968,COP,True,225,540,2.400000
17,4. DESeq2 paired input,437968,__rest__,True,59742,21373,0.357755
18,4. DESeq2 paired input,439247,COP,True,341,843,2.472141
19,4. DESeq2 paired input,439247,__rest__,True,74288,34103,0.459065
20,4. DESeq2 paired input,455228,COP,True,345,791,2.292754
21,4. DESeq2 paired input,455228,__rest__,True,62231,22645,0.363886
22,4. DESeq2 paired input,489830,COP,True,290,690,2.379310
23,4. DESeq2 paired input,489830,__rest__,True,50926,17649,0.346562
24,4. DESeq2 paired input,508467,COP,True,343,838,2.443149
25,4. DESeq2 paired input,508467,__rest__,True,65255,29759,0.456042
26,4. DESeq2 paired input,600598,COP,True,343,855,2.492711
27,4. DESeq2 paired input,600598,__rest__,True,75984,27755,0.365274
28,4. DESeq2 paired input,600599,COP,True,388,1150,2.963918
29,4. DESeq2 paired input,600599,__rest__,True,72769,28636,0.393519
30,4. DESeq2 paired input,600600,COP,True,312,721,2.310897
31,4. DESeq2 paired input,600600,__rest__,True,62909,23689,0.376560
32,4. DESeq2 paired input,602886,COP,True,232,578,2.491379
33,4. DESeq2 paired input,602886,__rest__,True,49072,23525,0.479398
34,4. DESeq2 paired input,602887,COP,True,246,644,2.617886
35,4. DESeq2 paired input,602887,__rest__,True,59886,23738,0.396386
36,4. DESeq2 paired input,631316,COP,True,334,958,2.868263
37,4. DESeq2 paired input,631316,__rest__,True,65014,30702,0.472237
38,4. DESeq2 paired input,631317,COP,True,309,874,2.828479
39,4. DESeq2 paired input,631317,__rest__,True,65375,30119,0.460711
40,4. DESeq2 paired input,632977,COP,True,347,732,2.109510
41,4. DESeq2 paired input,632977,__rest__,True,60082,24337,0.405063
42,4. DESeq2 paired input,664976,COP,True,295,627,2.125424
43,4. DESeq2 paired input,664976,__rest__,True,59407,24736,0.416382
44,4. DESeq2 paired input,671899,COP,True,254,467,1.838583
45,4. DESeq2 paired input,671899,__rest__,True,55157,24924,0.451874
46,4. DESeq2 paired input,671902,COP,True,271,674,2.487085
47,4. DESeq2 paired input,671902,__rest__,True,57706,22497,0.389855
48,4. DESeq2 paired input,710673,COP,True,350,779,2.225714
49,4. DESeq2 paired input,710673,__rest__,True,59824,20505,0.342755
50,4. DESeq2 paired input,730346,COP,True,231,584,2.528139
51,4. DESeq2 paired input,730346,__rest__,True,50732,21893,0.431542
52,4. DESeq2 paired input,730349,COP,True,294,776,2.639456
53,4. DESeq2 paired input,730349,__rest__,True,52628,24264,0.461047
54,4. DESeq2 paired input,755476,COP,True,235,514,2.187234
55,4. DESeq2 paired input,755476,__rest__,True,59633,23098,0.387336

Step 5. KaroSpace-formatted DE result for Arc

,source,reference,available,gene_present,method,counts_layer,n_source,n_reference,n_replicates,base_mean,log2FC,stat,pvalue,padj,pct_source,pct_rest,padj_cutoff,log2fc_cutoff,passes_DE_star,rank_in_sorted_result,n_result_genes
0,COP,__rest__,True,True,pseudobulk-deseq2,counts,8190,1705706,28,9054.05521,2.598985,93.24143,0.0,4.940656e-324,0.771551,0.163532,0.05,0.5,True,4,87

Step 6. DESeq2 sample diagnostics embedded by KaroSpace

                label replicate     group  n_cells  library_size
0        261982 | COP    261982       COP      273         18983
1   261982 | __rest__    261982  __rest__    57008       5772870
2        264010 | COP    264010       COP      257         17878
3   264010 | __rest__    264010  __rest__    58554       5846939
4        264011 | COP    264011       COP      266         21874
5   264011 | __rest__    264011  __rest__    61428       6650111
6        311430 | COP    311430       COP      244         20455
7   311430 | __rest__    311430  __rest__    58839       6646384
8        350670 | COP    350670       COP      244         19345
9   350670 | __rest__    350670  __rest__    62515       7013100
10       437942 | COP    437942       COP      293         20135
11  437942 | __rest__    437942  __rest__    61443       5786579
12       437943 | COP    437943       COP      282         22425
13  437943 | __rest__    437943  __rest__    60251       6551102
14       437944 | COP    437944       COP      346         24820
15  437944 | __rest__    437944  __rest__    67048       6535193
16       437968 | COP    437968       COP      225         17351
17  437968 | __rest__    437968  __rest__    59742       6222515
18       439247 | COP    439247       COP      341         22528
19  439247 | __rest__    439247  __rest__    74288       8069565
20       455228 | COP    455228       COP      345         22267
21  455228 | __rest__    455228  __rest__    62231       5735871
22       489830 | COP    489830       COP      290         22344
23  489830 | __rest__    489830  __rest__    50926       5042526
24       508467 | COP    508467       COP      343         24620
25  508467 | __rest__    508467  __rest__    65255       7184202
26       600598 | COP    600598       COP      343         29991
27  600598 | __rest__    600598  __rest__    75984       8492650
28       600599 | COP    600599       COP      388         36903
29  600599 | __rest__    600599  __rest__    72769       8561176
30       600600 | COP    600600       COP      312         23194
31  600600 | __rest__    600600  __rest__    62909       6291601
32       602886 | COP    602886       COP      232         16195
33  602886 | __rest__    602886  __rest__    49072       4786738
34       602887 | COP    602887       COP      246         19459
35  602887 | __rest__    602887  __rest__    59886       6904457
36       631316 | COP    631316       COP      334         26877
37  631316 | __rest__    631316  __rest__    65014       7115620
38       631317 | COP    631317       COP      309         25927
39  631317 | __rest__    631317  __rest__    65375       7320510
40       632977 | COP    632977       COP      347         21247
41  632977 | __rest__    632977  __rest__    60082       5399537
42       664976 | COP    664976       COP      295         18909
43  664976 | __rest__    664976  __rest__    59407       5995889
44       671899 | COP    671899       COP      254         14323
45  671899 | __rest__    671899  __rest__    55157       4930133
46       671902 | COP    671902       COP      271         20548
47  671902 | __rest__    671902  __rest__    57706       5961757
48       710673 | COP    710673       COP      350         24877
49  710673 | __rest__    710673  __rest__    59824       5916411
50       730346 | COP    730346       COP      231         18671
51  730346 | __rest__    730346  __rest__    50732       5435482
52       730349 | COP    730349       COP      294         24976
53  730349 | __rest__    730349  __rest__    52628       5828692
54       755476 | COP    755476       COP      235         14410
55  755476 | __rest__    755476  __rest__    59633       5610362

==========================================================================================
Sox10: Oligodendrocytes vs rest
==========================================================================================

,step,category,cells,Arc_positive_cells,pct_Arc_positive,Arc_counts_sum,Arc_mean_per_cell
0,1. source cells,Oligodendrocytes,283292,228833,0.807764,621113.0,2.192483
1,1. rest cells,all non-source categories,1430604,56424,0.039441,91772.0,0.064149

,step,source_mean,rest_mean,log2(source_mean / rest_mean),log2_with_tiny_pseudocount,note
0,2. pooled rough log2FC,2.192483,0.064149,5.094992,5.094992,This is not DESeq2; it is a rough pooled check.

Step 3. Pooled category components that make up source and rest

,is_source,category,cells,Arc_counts,Arc_mean_per_cell
11,True,Oligodendrocytes,283292,621113,2.192483
1,False,COP,8190,20152,2.460562
8,False,OPC,61452,46037,0.749154
7,False,Microglia / perivascular macrophages,70664,3589,0.050790
4,False,Ependymal cells,29216,895,0.030634
9,False,Pericytes / smooth muscle cells,52581,1479,0.028128
0,False,Astrocytes,244494,6274,0.025661
3,False,Endothelial cells,170126,3728,0.021913
6,False,Inhibitory neurons,198530,2925,0.014733
5,False,Excitatory neurons,531760,6248,0.011750
10,False,VLMC,46200,395,0.008550
2,False,Choroid plexus,17391,50,0.002875

Step 4. Paired replicates used by DESeq2: 28 / required 2

,step,replicate,_pb_group,included,cells,Arc_counts,Arc_mean_per_cell
0,4. DESeq2 paired input,261982,Oligodendrocytes,True,9121,22642,2.482403
1,4. DESeq2 paired input,261982,__rest__,True,48160,3113,0.064639
2,4. DESeq2 paired input,264010,Oligodendrocytes,True,9122,18065,1.980377
3,4. DESeq2 paired input,264010,__rest__,True,49689,2624,0.052808
4,4. DESeq2 paired input,264011,Oligodendrocytes,True,9268,18474,1.993310
5,4. DESeq2 paired input,264011,__rest__,True,52426,2869,0.054725
6,4. DESeq2 paired input,311430,Oligodendrocytes,True,10002,21584,2.157968
7,4. DESeq2 paired input,311430,__rest__,True,49081,3444,0.070170
8,4. DESeq2 paired input,350670,Oligodendrocytes,True,9846,24733,2.511985
9,4. DESeq2 paired input,350670,__rest__,True,52913,3703,0.069983
10,4. DESeq2 paired input,437942,Oligodendrocytes,True,10518,22600,2.148697
11,4. DESeq2 paired input,437942,__rest__,True,51218,3298,0.064391
12,4. DESeq2 paired input,437943,Oligodendrocytes,True,9400,21096,2.244255
13,4. DESeq2 paired input,437943,__rest__,True,51133,3132,0.061252
14,4. DESeq2 paired input,437944,Oligodendrocytes,True,12438,23634,1.900145
15,4. DESeq2 paired input,437944,__rest__,True,54956,3292,0.059902
16,4. DESeq2 paired input,437968,Oligodendrocytes,True,8989,19130,2.128157
17,4. DESeq2 paired input,437968,__rest__,True,50978,2783,0.054592
18,4. DESeq2 paired input,439247,Oligodendrocytes,True,12774,30235,2.366917
19,4. DESeq2 paired input,439247,__rest__,True,61855,4711,0.076162
20,4. DESeq2 paired input,455228,Oligodendrocytes,True,10955,20156,1.839890
21,4. DESeq2 paired input,455228,__rest__,True,51621,3280,0.063540
22,4. DESeq2 paired input,489830,Oligodendrocytes,True,8527,15899,1.864548
23,4. DESeq2 paired input,489830,__rest__,True,42689,2440,0.057158
24,4. DESeq2 paired input,508467,Oligodendrocytes,True,10930,26715,2.444190
25,4. DESeq2 paired input,508467,__rest__,True,54668,3882,0.071010
26,4. DESeq2 paired input,600598,Oligodendrocytes,True,11967,24326,2.032757
27,4. DESeq2 paired input,600598,__rest__,True,64360,4284,0.066563
28,4. DESeq2 paired input,600599,Oligodendrocytes,True,11802,25849,2.190222
29,4. DESeq2 paired input,600599,__rest__,True,61355,3937,0.064168
30,4. DESeq2 paired input,600600,Oligodendrocytes,True,9899,21366,2.158400
31,4. DESeq2 paired input,600600,__rest__,True,53322,3044,0.057087
32,4. DESeq2 paired input,602886,Oligodendrocytes,True,8774,21457,2.445521
33,4. DESeq2 paired input,602886,__rest__,True,40530,2646,0.065285
34,4. DESeq2 paired input,602887,Oligodendrocytes,True,9445,21029,2.226469
35,4. DESeq2 paired input,602887,__rest__,True,50687,3353,0.066151
36,4. DESeq2 paired input,631316,Oligodendrocytes,True,11072,27560,2.489162
37,4. DESeq2 paired input,631316,__rest__,True,54276,4100,0.075540
38,4. DESeq2 paired input,631317,Oligodendrocytes,True,12233,26932,2.201586
39,4. DESeq2 paired input,631317,__rest__,True,53451,4061,0.075976
40,4. DESeq2 paired input,632977,Oligodendrocytes,True,9178,21590,2.352364
41,4. DESeq2 paired input,632977,__rest__,True,51251,3479,0.067882
42,4. DESeq2 paired input,664976,Oligodendrocytes,True,10165,22261,2.189966
43,4. DESeq2 paired input,664976,__rest__,True,49537,3102,0.062620
44,4. DESeq2 paired input,671899,Oligodendrocytes,True,10914,22691,2.079073
45,4. DESeq2 paired input,671899,__rest__,True,44497,2700,0.060678
46,4. DESeq2 paired input,671902,Oligodendrocytes,True,9839,20007,2.033438
47,4. DESeq2 paired input,671902,__rest__,True,48138,3164,0.065728
48,4. DESeq2 paired input,710673,Oligodendrocytes,True,8532,18274,2.141819
49,4. DESeq2 paired input,710673,__rest__,True,51642,3010,0.058286
50,4. DESeq2 paired input,730346,Oligodendrocytes,True,8689,19948,2.295776
51,4. DESeq2 paired input,730346,__rest__,True,42274,2529,0.059824
52,4. DESeq2 paired input,730349,Oligodendrocytes,True,9356,22088,2.360838
53,4. DESeq2 paired input,730349,__rest__,True,43566,2952,0.067759
54,4. DESeq2 paired input,755476,Oligodendrocytes,True,9537,20772,2.178043
55,4. DESeq2 paired input,755476,__rest__,True,50331,2840,0.056426

Step 5. KaroSpace-formatted DE result for Arc

,source,reference,available,gene_present,n_result_genes,method,min_pct_expressed,rank_in_sorted_result
0,Oligodendrocytes,__rest__,True,False,89,pseudobulk-deseq2,0.1,None

Step 6. DESeq2 sample diagnostics embedded by KaroSpace

,label,replicate,group,n_cells,library_size
0,261982 | Oligodendrocytes,261982,Oligodendrocytes,9121,822830
1,261982 | __rest__,261982,__rest__,48160,4969023
2,264010 | Oligodendrocytes,264010,Oligodendrocytes,9122,791386
3,264010 | __rest__,264010,__rest__,49689,5073431
4,264011 | Oligodendrocytes,264011,Oligodendrocytes,9268,764705
5,264011 | __rest__,264011,__rest__,52426,5907280
6,311430 | Oligodendrocytes,311430,Oligodendrocytes,10002,907283
7,311430 | __rest__,311430,__rest__,49081,5759556
8,350670 | Oligodendrocytes,350670,Oligodendrocytes,9846,984114
9,350670 | __rest__,350670,__rest__,52913,6048331
10,437942 | Oligodendrocytes,437942,Oligodendrocytes,10518,934198
11,437942 | __rest__,437942,__rest__,51218,4872516
12,437943 | Oligodendrocytes,437943,Oligodendrocytes,9400,840454
13,437943 | __rest__,437943,__rest__,51133,5733073
14,437944 | Oligodendrocytes,437944,Oligodendrocytes,12438,999704
15,437944 | __rest__,437944,__rest__,54956,5560309
16,437968 | Oligodendrocytes,437968,Oligodendrocytes,8989,782260
17,437968 | __rest__,437968,__rest__,50978,5457606
18,439247 | Oligodendrocytes,439247,Oligodendrocytes,12774,1176333
19,439247 | __rest__,439247,__rest__,61855,6915760
20,455228 | Oligodendrocytes,455228,Oligodendrocytes,10955,866558
21,455228 | __rest__,455228,__rest__,51621,4891580
22,489830 | Oligodendrocytes,489830,Oligodendrocytes,8527,701178
23,489830 | __rest__,489830,__rest__,42689,4363692
24,508467 | Oligodendrocytes,508467,Oligodendrocytes,10930,1097805
25,508467 | __rest__,508467,__rest__,54668,6111017
26,600598 | Oligodendrocytes,600598,Oligodendrocytes,11967,1078572
27,600598 | __rest__,600598,__rest__,64360,7444069
28,600599 | Oligodendrocytes,600599,Oligodendrocytes,11802,1070473
29,600599 | __rest__,600599,__rest__,61355,7527606
30,600600 | Oligodendrocytes,600600,Oligodendrocytes,9899,857534
31,600600 | __rest__,600600,__rest__,53322,5457261
32,602886 | Oligodendrocytes,602886,Oligodendrocytes,8774,822651
33,602886 | __rest__,602886,__rest__,40530,3980282
34,602887 | Oligodendrocytes,602887,Oligodendrocytes,9445,923199
35,602887 | __rest__,602887,__rest__,50687,6000717
36,631316 | Oligodendrocytes,631316,Oligodendrocytes,11072,1066306
37,631316 | __rest__,631316,__rest__,54276,6076191
38,631317 | Oligodendrocytes,631317,Oligodendrocytes,12233,1070068
39,631317 | __rest__,631317,__rest__,53451,6276369
40,632977 | Oligodendrocytes,632977,Oligodendrocytes,9178,791409
41,632977 | __rest__,632977,__rest__,51251,4629375
42,664976 | Oligodendrocytes,664976,Oligodendrocytes,10165,897251
43,664976 | __rest__,664976,__rest__,49537,5117547
44,671899 | Oligodendrocytes,671899,Oligodendrocytes,10914,893587
45,671899 | __rest__,671899,__rest__,44497,4050869
46,671902 | Oligodendrocytes,671902,Oligodendrocytes,9839,793433
47,671902 | __rest__,671902,__rest__,48138,5188872
48,710673 | Oligodendrocytes,710673,Oligodendrocytes,8532,759154
49,710673 | __rest__,710673,__rest__,51642,5182134
50,730346 | Oligodendrocytes,730346,Oligodendrocytes,8689,766713
51,730346 | __rest__,730346,__rest__,42274,4687440
52,730349 | Oligodendrocytes,730349,Oligodendrocytes,9356,850676
53,730349 | __rest__,730349,__rest__,43566,5002992
54,755476 | Oligodendrocytes,755476,Oligodendrocytes,9537,769379
55,755476 | __rest__,755476,__rest__,50331,4855393

,source,source_mean,rest_mean,rough_log2fc_tiny_pseudocount,DESeq2_log2FC,DESeq2_padj,pct_source,pct_rest,passes_DE_star,included_replicates
0,COP,2.460562,0.406127,2.598985,2.598985,4.940656e-324,0.771551,0.163532,True,"261982, 264010, 264011, 311430, 350670, 437942..."
1,Oligodendrocytes,2.192483,0.064149,5.094992,NaN,NaN,NaN,NaN,None,"261982, 264010, 264011, 311430, 350670, 437942..."

In [16]:
# Pooled category means for Arc. These correspond to the values used by DATA.cluster_gene_means.
pooled = (
    pb_meta.groupby("category", observed=True)
    .agg(n_cells=("n_cells", "sum"), gene_counts=("gene_counts", "sum"))
    .reset_index()
)
pooled["mean_per_cell"] = pooled["gene_counts"] / pooled["n_cells"].replace(0, np.nan)
pooled["is_target_source"] = pooled["category"].isin(source_labels)
pooled.sort_values(["is_target_source", "mean_per_cell"], ascending=[False, False]).head(30)

,category,n_cells,gene_counts,mean_per_cell,is_target_source
1,COP,8190,20152,2.460562,True
9,Oligodendrocytes,283292,621113,2.192483,True
8,OPC,61452,46037,0.749154,False
7,Microglia / perivascular macrophages,70664,3589,0.050790,False
4,Ependymal cells,29216,895,0.030634,False
10,Pericytes / smooth muscle cells,52581,1479,0.028128,False
0,Astrocytes,244494,6274,0.025661,False
3,Endothelial cells,170126,3728,0.021913,False
6,Inhibitory neurons,198530,2925,0.014733,False
5,Excitatory neurons,531760,6248,0.011750,False
11,VLMC,46200,395,0.008550,False
2,Choroid plexus,17391,50,0.002875,False

## Interpretation checklist

- A balanced-rest result compares one category with the equally weighted mean of the other retained annotation coefficients from the shared model.
- The displayed pooled all-other-cells mean is descriptive only and should not be interpreted as the tested DESeq2 reference.
- If `available=False`, inspect `reason`, `details`, `n_source`, and `n_reference`.
- If log2FC is high but adjusted p-value is above the cutoff, replicate-level variability or multiple-testing correction can explain the result.